services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: savewithme
      POSTGRES_USER: savewithme
      POSTGRES_PASSWORD: savewithme
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U savewithme"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
      args:
        BASE_IMAGE: ${DOCKER_IMAGE_BASE:-public.ecr.aws/amazoncorretto:21-alpine}
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/savewithme
      SPRING_DATASOURCE_USERNAME: savewithme
      SPRING_DATASOURCE_PASSWORD: savewithme
      SPRING_PROFILES_ACTIVE: ${APP_PROFILE:-dev}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  dbdata:
