name: Release - Build & Push Image (prod)

on:
  release:
    types: [published]

concurrency:
  group: release-${{ github.event.release.tag_name }}
  cancel-in-progress: false

jobs:
  build-push-prod:
    environment: prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TAG_RAW: ${{ github.event.release.tag_name }} # ex: v1.2.3
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ vars.JAVA_TOOLCHAIN_VERSION || 21 }}
          cache: maven

      - name: Build JAR
        working-directory: app
        run: mvn -B -U -ntp -DskipTests package

      - name: Normalize tag (remove leading 'v')
        id: norm
        run: |
          CLEAN_TAG="${TAG_RAW#v}"
          echo "TAG=${TAG_RAW}" >> $GITHUB_ENV
          echo "CLEAN_TAG=${CLEAN_TAG}" >> $GITHUB_ENV
          echo "clean_tag=$CLEAN_TAG" >> $GITHUB_OUTPUT

      - name: Build & tag image
        working-directory: infra/docker
        env:
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          AWS_REGION:     ${{ vars.AWS_REGION }}
          ECR_REPO:       ${{ vars.ECR_REPO }}
          DOCKER_IMAGE_BASE: ${{ vars.DOCKER_IMAGE_BASE }}
        run: |
          IMAGE=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}
          docker build \
            -t ${IMAGE}:${TAG} \
            -t ${IMAGE}:${{ steps.norm.outputs.clean_tag }} \
            -t ${IMAGE}:latest \
            --build-arg BASE_IMAGE="${DOCKER_IMAGE_BASE}" \
            -f Dockerfile ../../

      - name: Push
        env:
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          AWS_REGION:     ${{ vars.AWS_REGION }}
          ECR_REPO:       ${{ vars.ECR_REPO }}
        run: |
          IMAGE=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}
          docker push ${IMAGE}:${TAG}
          docker push ${IMAGE}:${{ steps.norm.outputs.clean_tag }}
          docker push ${IMAGE}:latest

      - name: WhoAmI (AWS)
        run: aws sts get-caller-identity
